"""`lab explain`: a generated summary of a finished run."""

from __future__ import annotations

import functools
from typing import Annotated

import typer
from lab_llm.prompts import render_run_explanation

from lab_cli.exit_codes import ExitCode
from lab_cli.identifiers import parse_id
from lab_cli.options import JSON_OPTION
from lab_cli.output import emit, run_or_fail
from lab_cli.runtime import (
    actor,
    default_artifact_store,
    default_audit_log,
    default_language_model,
    default_run_store,
    prompt_template_dir,
    scratch_root,
)
from lab_domain.ids import RunId
from lab_domain.services.explain_service import Explanation, explain_run


def explain(
    run_id: Annotated[str, typer.Argument(help="Run identifier, e.g. RUN-000001.")],
    json_output: Annotated[bool, JSON_OPTION] = False,
    model: Annotated[
        str | None,
        typer.Option("--model", help="Model to use, overriding the configured one."),
    ] = None,
) -> None:
    """Summarise a finished run in prose. Optional: needs a configured model.

    The summary is generated text, stored as its own artifact alongside the
    exact prompt that was sent. It never becomes part of the run record.
    """

    def action() -> Explanation:
        return explain_run(
            parse_id(RunId, run_id),
            store=default_run_store(),
            artifacts=default_artifact_store(),
            model=default_language_model(model),
            render_prompt=functools.partial(
                render_run_explanation, prompt_template_dir()
            ),
            scratch_root=scratch_root(),
            audit=default_audit_log(),
            actor=actor(),
        )

    explanation = run_or_fail(json_output, action)
    emit(
        {
            "run_id": str(explanation.run_id),
            "provider": explanation.provider,
            "model": explanation.model,
            "text": explanation.text,
            "artifact": {
                "id": str(explanation.artifact.id),
                "name": explanation.artifact.name,
                "uri": explanation.artifact.uri,
            },
            "prompt_artifact": {
                "id": str(explanation.prompt_artifact.id),
                "name": explanation.prompt_artifact.name,
                "uri": explanation.prompt_artifact.uri,
            },
        },
        "\n".join(
            [
                f"{explanation.run_id}: generated by {explanation.provider}"
                f"/{explanation.model}",
                "",
                explanation.text,
                "",
                "Generated text, not evidence. The facts are in "
                f"`lab status {explanation.run_id}` and the report.",
                f"Stored: {explanation.artifact.uri}",
                f"Prompt: {explanation.prompt_artifact.uri}",
            ]
        ),
        json_output,
    )
    raise typer.Exit(int(ExitCode.OK))
