"""Minimal demo model generated by `lab init`.

Reads a flat YAML config of scalars and writes results to the output directory:
``summary.json`` with the resolved configuration, and ``metrics.json``, which
the platform picks up as the run's main metrics. Kept dependency-free so it
runs in any Python 3.12 environment.
"""

import argparse
import json
import os
from pathlib import Path


def load_config(path: Path) -> dict[str, object]:
    config: dict[str, object] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        key, _, value = line.partition(":")
        try:
            config[key.strip()] = json.loads(value.strip())
        except json.JSONDecodeError:
            config[key.strip()] = value.strip()
    return config


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the demo model.")
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument(
        "--output-dir",
        default=Path(os.environ.get("LAB_OUTPUT_DIR", "results")),
        type=Path,
    )
    args = parser.parse_args()

    config = load_config(args.config)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    repetitions = int(config.get("repetitions", 1))
    seed = int(config.get("seed", 0))
    # Stand-in for a real computation: replace with the model under study.
    score = round((seed % 100) / 100 + repetitions * 0.01, 4)

    summary = {"status": "ok", "config": config}
    (args.output_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    metrics = {"repetitions": repetitions, "seed": seed, "score": score}
    (args.output_dir / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n")


if __name__ == "__main__":
    main()
