"""Minimal demo model generated by `lab init`.

Reads a flat YAML config of scalars and writes summary.json to the output
directory. Kept dependency-free so it runs in any Python 3.12 environment.
"""

import argparse
import json
from pathlib import Path


def load_config(path: Path) -> dict[str, object]:
    config: dict[str, object] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        key, _, value = line.partition(":")
        try:
            config[key.strip()] = json.loads(value.strip())
        except json.JSONDecodeError:
            config[key.strip()] = value.strip()
    return config


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the demo model.")
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--output-dir", default=Path("results"), type=Path)
    args = parser.parse_args()

    config = load_config(args.config)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    summary = {"status": "ok", "config": config}
    (args.output_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")


if __name__ == "__main__":
    main()
