"""A fake SLURM cluster: sbatch, squeue, sacct and scancel.

The four executables are generated into a directory that tests put first on
PATH, so the platform talks to them exactly as it would to a real scheduler,
through argument lists and machine-readable output.

The fake keeps its state in one JSON file. A submitted job stays queued until
something asks it to start, which lets a test drive the queued → running →
completed sequence deliberately rather than racing it.
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path

STATE_FILENAME = "cluster.json"

_PREAMBLE = '''#!/usr/bin/env python3
"""Generated by tests/fixtures/fake_slurm.py. Not a real scheduler."""
import json
import os
import subprocess
import sys
from pathlib import Path

STATE = Path(os.environ["FAKE_SLURM_STATE"])


def load():
    if not STATE.exists():
        return {"next_id": 4200, "jobs": {}}
    return json.loads(STATE.read_text())


def save(state):
    STATE.parent.mkdir(parents=True, exist_ok=True)
    STATE.write_text(json.dumps(state, indent=2))
'''

_SBATCH = (
    _PREAMBLE
    + """

def main():
    arguments = sys.argv[1:]
    script = arguments[-1]
    state = load()
    job_id = str(state["next_id"])
    state["next_id"] += 1
    state["jobs"][job_id] = {"state": "PENDING", "script": script, "exit_code": None}
    save(state)
    if "--parsable" in arguments:
        print(job_id)
    else:
        print(f"Submitted batch job {job_id}")
    # Autostart mode runs the job immediately, the way a cluster with a free
    # node would.
    if os.environ.get("FAKE_SLURM_AUTOSTART") == "1":
        runner = sys.argv[0].replace("sbatch", "fake-run")
        subprocess.run([sys.executable, runner, job_id])
    return 0


sys.exit(main())
"""
)

_FAKE_RUN = (
    _PREAMBLE
    + '''

def directive(script_text, name):
    """Read a #SBATCH directive out of the job script, as slurmd would."""
    marker = f"#SBATCH --{name}="
    for line in script_text.splitlines():
        if line.startswith(marker):
            return line[len(marker):].strip().strip("'\\"")
    return None


def main():
    job_id = sys.argv[1]
    state = load()
    job = state["jobs"][job_id]
    job["state"] = "RUNNING"
    save(state)

    script_text = Path(job["script"]).read_text()
    stdout_path = Path(directive(script_text, "output"))
    stderr_path = Path(directive(script_text, "error"))
    stdout_path.parent.mkdir(parents=True, exist_ok=True)
    stderr_path.parent.mkdir(parents=True, exist_ok=True)
    with stdout_path.open("w") as out, stderr_path.open("w") as err:
        completed = subprocess.run(["bash", job["script"]], stdout=out, stderr=err)

    state = load()
    job = state["jobs"][job_id]
    job["exit_code"] = completed.returncode
    job["state"] = "COMPLETED" if completed.returncode == 0 else "FAILED"
    save(state)
    return 0


sys.exit(main())
'''
)

_SQUEUE = (
    _PREAMBLE
    + """

def main():
    arguments = sys.argv[1:]
    job_id = arguments[arguments.index("--job") + 1]
    job = load()["jobs"].get(job_id)
    # A job that has finished has left the queue: squeue prints nothing.
    if job is None or job["state"] in {"COMPLETED", "FAILED", "CANCELLED", "TIMEOUT"}:
        return 0
    print(job["state"])
    return 0


sys.exit(main())
"""
)

_SACCT = (
    _PREAMBLE
    + """

def main():
    arguments = sys.argv[1:]
    job_id = arguments[arguments.index("--jobs") + 1]
    job = load()["jobs"].get(job_id)
    if job is None:
        return 0
    code = job["exit_code"] if job["exit_code"] is not None else 0
    print(f"{job['state']}|{code}:0|2026-07-26T12:00:00")
    return 0


sys.exit(main())
"""
)

_SCANCEL = (
    _PREAMBLE
    + """

def main():
    job_id = sys.argv[1]
    state = load()
    job = state["jobs"].get(job_id)
    if job is None:
        print(f"scancel: error: Invalid job id {job_id}", file=sys.stderr)
        return 1
    job["state"] = "CANCELLED"
    job["exit_code"] = 0
    save(state)
    return 0


sys.exit(main())
"""
)

_EXECUTABLES = {
    "sbatch": _SBATCH,
    "squeue": _SQUEUE,
    "sacct": _SACCT,
    "scancel": _SCANCEL,
    "fake-run": _FAKE_RUN,
}


def install(directory: Path) -> Path:
    """Write the fake cluster's executables into ``directory``."""
    directory.mkdir(parents=True, exist_ok=True)
    for name, source in _EXECUTABLES.items():
        path = directory / name
        path.write_text(source, encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return directory


def environment(
    bin_dir: Path, state_path: Path, *, autostart: bool = True
) -> dict[str, str]:
    """Environment that points the platform at the fake cluster."""
    return {
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_SLURM_STATE": str(state_path),
        "FAKE_SLURM_AUTOSTART": "1" if autostart else "0",
    }


def start_job(bin_dir: Path, state_path: Path, job_id: str) -> None:
    """Run a queued job, as a scheduler would when a node frees up."""
    import subprocess
    import sys

    subprocess.run(
        [sys.executable, str(bin_dir / "fake-run"), job_id],
        env={**os.environ, "FAKE_SLURM_STATE": str(state_path)},
        check=True,
    )


def job_state(state_path: Path, job_id: str) -> str:
    return json.loads(state_path.read_text())["jobs"][job_id]["state"]
